name: Kernel Build with ARM Toolchain and NetHunter Patches

on:
  push:
    branches:
      - WIP  # Triggers the action on pushes to the WIP branch
  pull_request:
    branches:
      - WIP  # Optionally build on pull requests to the WIP branch

jobs:
  build:
    runs-on: ubuntu-latest  # The environment to run on (Ubuntu)

    steps:
    - name: Checkout Nethunter kernel source
      uses: actions/checkout@v3
      with:
        repository: MK-986123/Nethunter_kernel_samsung_dm3q
        ref: WIP  # Using 'WIP' branch for Nethunter kernel
        fetch-depth: 0  # Ensures full history is fetched
        clean: true  # Cleans any previous files

    - name: Checkout AnyKernel3 source
      uses: actions/checkout@v3
      with:
        repository: MK-986123/AnyKernel3
        ref: master  # Using 'master' branch for AnyKernel3
        path: AnyKernel3
        fetch-depth: 0  # Ensures full history is fetched
        clean: true  # Cleans any previous files

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang llvm lld git bc bison flex libncurses5-dev curl zip
        # Install additional dependencies required for kernel building
        sudo apt-get install -y libssl-dev libelf-dev libncurses-dev python3-pip
        pip3 install kconfiglib

    - name: Download ARM toolchain
      run: |
        # Download and extract ARM's AArch64 toolchain
        wget https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/aarch64-none-elf/gcc-arm-12.2-2022.12-x86_64-aarch64-none-elf.tar.xz
        tar -xvf gcc-arm-12.2-2022.12-x86_64-aarch64-none-elf.tar.xz
        # Set the toolchain path
        export ARM_TOOLCHAIN=$(pwd)/gcc-arm-12.2-2022.12-x86_64-aarch64-none-elf

    - name: Apply NetHunter Patches
      run: |
        # Apply patches for USB HID, WiFi injection, Bluetooth RFCOMM, and other NetHunter features
        git apply patches/usb_hid_gadget.patch
        git apply patches/wifi_injection.patch
        git apply patches/bluetooth_rfcomm.patch

    - name: Configure kernel for NetHunter
      run: |
        # Export environment variables for ARM toolchain
        export ARCH=arm64
        export CROSS_COMPILE=$ARM_TOOLCHAIN/bin/aarch64-none-elf-  # Use ARM's toolchain
        export KERNEL_SOURCE=https://github.com/MK-986123/Nethunter_kernel_samsung_dm3q
        export CLANG_PATH=$(pwd)/clang/bin
        export PATH=$CLANG_PATH:$PATH

        # Clean any previous build artifacts
        make clean && make mrproper

        # Check the kernel configuration and enable features for NetHunter
        make kalama-gki_defconfig O=out
        make menuconfig O=out  # Optionally add kernel features if needed (HID, USB Gadget, Bluetooth, etc.)

    - name: Build the kernel with ARM toolchain
      run: |
        # Build the kernel using ARM's toolchain and clang
        make -j$(nproc) CC=clang LD=ld.lld KBUILD_COMPILER_STRING="Clang $(clang --version)" O=out

    - name: Package the kernel with AnyKernel3
      run: |
        # Copy compiled kernel to AnyKernel3 directory
        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        
        # Create a flashable zip
        cd AnyKernel3
        zip -r9 kernel.zip ./*
        cd ..

    - name: Upload kernel.zip artifact
      uses: actions/upload-artifact@v3
      with:
        name: kernel.zip
        path: AnyKernel3/kernel.zip
