name: Build NetHunter Kernel

on:
  push:
    branches:
      - WIP

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up GCC Toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      env:
        GCC_PATH: /usr/bin/aarch64-linux-gnu-gcc

    - name: Download Toolchain from Google Drive
      run: |
        pip install gdown
        gdown https://drive.google.com/uc?id=19L40u5xz02NfwnlkevfX_fCwaFLjBqiY -O toolchain.tar.gz
        tar -xzvf toolchain.tar.gz
      env:
        GCC_PATH: ${{ github.workspace }}/gcc-arm

    - name: Verify Toolchain Path
      run: |
        if [ ! -f "${GCC_PATH}/bin/aarch64-linux-gnu-gcc" ]; then
          echo "Error: Toolchain not found at ${GCC_PATH}"
          exit 1
        fi

    - name: Configure Kernel (defconfig)
      run: |
        make ARCH=arm64 CROSS_COMPILE=${GCC_PATH}/bin/aarch64-linux-gnu- kalama-gki_defconfig

    - name: Build Kernel
      run: |
        make -j$(nproc) ARCH=arm64 CROSS_COMPILE=${GCC_PATH}/bin/aarch64-linux-gnu-

    - name: Verify Kernel Build
      run: |
        file arch/arm64/boot/Image || { echo "Kernel image not found!"; exit 1; }

    - name: Download and Integrate AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3.git anykernel
        cp arch/arm64/boot/Image anykernel/zImage
        cd anykernel
        zip -r9 anykernel.zip *

    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Nethunter-Kernel
        path: anykernel/anykernel.zip
