name: NetHunter Kernel Build for Samsung S23 Ultra (SM-S916B)

on:
  push:
    branches:
      - WIP
  pull_request:
    branches:
      - WIP

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEFCONFIG: "kalama-gki_defconfig"
      GCC_PATH: "/opt/gcc-arm"
      BUILD_OUTPUT: "output/"
    
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: kernel

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison flex libssl-dev build-essential \
          ccache libncurses5-dev libelf-dev libudev-dev libpci-dev wget curl git \
          xz-utils fakeroot rsync dwarves python3

      - name: Install gdown
        run: |
          pip install gdown

      - name: Download Toolchain from Google Drive
        run: |
          gdown https://drive.google.com/uc?id=19L40u5xz02NfwnlkevfX_fCwaFLjBqiY -O toolchain.tar.gz
          mkdir -p ${GCC_PATH}
          tar -xf toolchain.tar.gz -C ${GCC_PATH}
          export PATH=${GCC_PATH}/bin:$PATH

      - name: Verify Toolchain
        run: |
          if [ ! -d "${GCC_PATH}" ]; then
            echo "Error: Toolchain extraction failed!"
            exit 1
          fi

      - name: Configure Kernel (defconfig)
        working-directory: ./kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          make ${DEFCONFIG}

      - name: Build Kernel
        working-directory: ./kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=${GCC_PATH}/bin/aarch64-linux-gnu-
          make -j$(nproc) O=${BUILD_OUTPUT} ARCH=arm64 CROSS_COMPILE=${GCC_PATH}/bin/aarch64-linux-gnu-

      - name: Verify Kernel Build
        run: |
          ls ${BUILD_OUTPUT}
          if [ ! -f "${BUILD_OUTPUT}/Image.gz" ]; then
            echo "Error: Kernel image not
