name: Kernel Build with Fixes for Missing Files and Kbuild Errors

on:
  push:
    branches:
      - WIP  # Triggers the action on pushes to the WIP branch
  pull_request:
    branches:
      - WIP  # Optionally build on pull requests to the WIP branch

jobs:
  build:
    runs-on: ubuntu-latest  # The environment to run on (Ubuntu)

    steps:
    - name: Checkout Nethunter kernel source
      uses: actions/checkout@v3
      with:
        repository: MK-986123/Nethunter_kernel_samsung_dm3q
        ref: WIP  # Using 'WIP' branch for Nethunter kernel
        fetch-depth: 0  # Ensures full history is fetched
        clean: true  # Cleans any previous files

    - name: Checkout AnyKernel3 source
      uses: actions/checkout@v3
      with:
        repository: MK-986123/AnyKernel3
        ref: master  # Using 'master' branch for AnyKernel3
        path: AnyKernel3
        fetch-depth: 0  # Ensures full history is fetched
        clean: true  # Cleans any previous files

    - name: Set up build environment
      run: |
        # Update the system and install required build tools
        sudo apt-get update
        sudo apt-get install -y build-essential git bc bison flex libncurses5-dev curl zip libssl-dev libelf-dev python3-pip
        # Install the toolchains from the Ubuntu repository
        sudo apt-get install -y clang llvm lld gcc-aarch64-linux-gnu
        # Install kconfiglib for menuconfig support
        pip3 install kconfiglib

    - name: Create custom kernel config for NetHunter with logging disabled
      run: |
        # Disable performance events (perf logging) and add NetHunter configs
        echo "CONFIG_USB_GADGET=y" >> nethunter_defconfig
        echo "CONFIG_HID_GADGET=y" >> nethunter_defconfig
        echo "CONFIG_USB_F_ACM=y" >> nethunter_defconfig
        echo "CONFIG_USB_F_HID=y" >> nethunter_defconfig
        echo "CONFIG_CFG80211=y" >> nethunter_defconfig
        echo "CONFIG_MAC80211=y" >> nethunter_defconfig
        echo "CONFIG_BT=y" >> nethunter_defconfig
        echo "CONFIG_BT_RFCOMM=y" >> nethunter_defconfig
        echo "CONFIG_BT_RFCOMM_TTY=y" >> nethunter_defconfig
        echo "CONFIG_EXT4_FS=y" >> nethunter_defconfig
        echo "CONFIG_VFAT_FS=y" >> nethunter_defconfig
        echo "CONFIG_PERF_EVENTS=n" >> nethunter_defconfig

    - name: Patch Kbuild for qcacld-3.0 to fix patsubst error
      run: |
        # Use a different delimiter (|) and ensure that the slashes are escaped correctly
        sed -i 's|$(patsubst %.c,%.o,$(wildcard ./*.c))|$(patsubst %.c,%.o,$(wildcard ./%.c))|' drivers/staging/qcacld-3.0/Kbuild

    - name: Thorough Cleanup of Source Tree
      run: |
        # Ensure that the source tree is cleaned up properly
        make mrproper

        # Force delete the 'out' directory and related artifacts if it exists
        rm -rf out
        rm -rf include/config
        rm -rf include/generated

        # Clean again just to ensure all remnants are gone
        make clean

    - name: Configure kernel for NetHunter
      run: |
        # Export environment variables for Clang and cross-compiler
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-  # Us
