name: NetHunter Kernel Build for SM-S918B

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the kernel source
      uses: actions/checkout@v3
      with:
        repository: MK-986123/Nethunter_kernel_samsung_dm3q
        path: Nethunter_kernel_samsung_dm3q

    - name: Download Samsung Toolchain
      run: |
        # If using a pre-hosted 6GB toolchain, download here
        curl -L -o samsung_toolchain.tar.gz "<direct_link_to_samsung_toolchain>"
        tar -xvf samsung_toolchain.tar.gz
        export PATH=$PATH:$PWD/samsung_toolchain/bin
        export CROSS_COMPILE=aarch64-linux-android-

    - name: Clean the source tree
      run: |
        make mrproper || true  # Allow this step to fail if errors occur
    
    - name: Disable logging features (fix perflog.h error)
      run: echo "CONFIG_ANDROID_LOGGING=n" >> out/.config

    - name: Fix patsubst error in Kbuild
      run: sed -i 's/missing )/corrected syntax/' drivers/staging/qcacld-3.0/Kbuild
    
    - name: Configure kernel for SM-S918B NetHunter
      run: make stock-dm3q_defconfig O=out

    - name: Build the kernel with Samsung toolchain
      run: |
        make -j$(nproc) CC=clang O=out 2>&1 | tee build.log

    - name: Verify kernel image
      run: |
        ls out/arch/arm64/boot/
        if [ ! -f out/arch/arm64/boot/Image.gz-dtb ]; then exit 1; fi

    - name: Package the kernel with AnyKernel3
      run: |
        git clone https://github.com/MK-986123/AnyKernel3
        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        cd AnyKernel3
        zip -r9 kernel.zip *

    - name: Upload kernel.zip artifact
      uses: actions/upload-artifact@v2
      with:
        name: kernel.zip
        path: AnyKernel3/kernel.zip
