name: Kernel Build with Samsung SM-S901E Toolchain

on:
  push:
    branches:
      - WIP
  pull_request:
    branches:
      - WIP

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Nethunter kernel source
      uses: actions/checkout@v3
      with:
        repository: MK-986123/Nethunter_kernel_samsung_dm3q
        ref: WIP
        fetch-depth: 0
        clean: true

    - name: Checkout AnyKernel3 source
      uses: actions/checkout@v3
      with:
        repository: MK-986123/AnyKernel3
        ref: master
        path: AnyKernel3
        fetch-depth: 0
        clean: true

    - name: Set up Samsung SM-S901E toolchain
      run: |
        # Clone the Samsung toolchain repo
        git clone https://github.com/iamimmanuelraj/toolchain_samsung_SM_S901E.git

        # Export paths for the toolchain
        export TOOLCHAIN_DIR=$PWD/toolchain_samsung_SM_S901E/prebuilts/clang/host/linux-x86/clang-r416183b/bin
        export PATH=$PATH:$TOOLCHAIN_DIR
        export CROSS_COMPILE=$TOOLCHAIN_DIR/aarch64-linux-gnu-

    - name: Configure kernel for NetHunter
      run: |
        export ARCH=arm64

        # Use the kalama_gki_defconfig or stock-dm3q_defconfig b
